server:
  port: 88
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/commons-data-collect?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456

